export default {
  GET_REPLIES_REQUEST: 'GET_REPLIES_REQUEST',
  GET_REPLIES_SUCCESS: 'GET_REPLIES_SUCCESS',
  GET_REPLIES_FAILURE: 'GET_REPLIES_FAILURE',

  GET_ALL_REPLIES_REQUEST: 'GET_ALL_REPLIES_REQUEST',
  GET_ALL_REPLIES_SUCCESS: 'GET_ALL_REPLIES_SUCCESS',
  GET_ALL_REPLIES_FAILURE: 'GET_ALL_REPLIES_FAILURE',

  GET_REPLY_COMMENT_REQUEST: 'GET_REPLY_COMMENT_REQUEST',
  GET_REPLY_COMMENT_SUCCESS: 'GET_REPLY_COMMENT_SUCCESS',
  GET_REPLY_COMMENT_FAILURE: 'GET_REPLY_COMMENT_FAILURE',

  POST_REPLY_REQUEST: 'POST_REPLY_REQUEST',
  POST_REPLY_SUCCESS: 'POST_REPLY_SUCCESS',
  POST_REPLY_FAILURE: 'POST_REPLY_FAILURE',

  DELETE_REPLY_REQUEST: 'DELETE_REPLY_REQUEST',
  DELETE_REPLY_SUCCESS: 'DELETE_REPLY_SUCCESS',
  DELETE_REPLY_FAILURE: 'DELETE_REPLY_FAILURE',

  SET_REPLIES: 'SET_REPLIES',
  INIT_SET_REPLIES: 'INIT_SET_REPLIES',
  ADD_REPLY: 'ADD_REPLY',
};
