export default {
  GET_ANNOUNCEMENTS_REQUEST: 'GET_ANNOUNCEMENTS_REQUEST',
  GET_ANNOUNCEMENTS_SUCCESS: 'GET_ANNOUNCEMENTS_SUCCESS',
  GET_ANNOUNCEMENTS_FAILURE: 'GET_ANNOUNCEMENTS_FAILURE',

  POST_ANNOUNCEMENT_SEEN_REQUEST: 'POST_ANNOUNCEMENT_SEEN_REQUEST',
  POST_ANNOUNCEMENT_SEEN_SUCCESS: 'POST_ANNOUNCEMENT_SEEN_SUCCESS',
  POST_ANNOUNCEMENT_SEEN_FAILURE: 'POST_ANNOUNCEMENT_SEEN_FAILURE',
};
