export default {
  GET_COMMENTS_REQUEST: 'GET_COMMENTS_REQUEST',
  GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
  GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',
  SET_COMMENTS: 'SET_COMMENTS',
  ADD_COMMENT: 'ADD_COMMENT',

  POST_COMMENT_REQUEST: 'POST_COMMENT_REQUEST',
  POST_COMMENT_SUCCESS: 'POST_COMMENT_SUCCESS',
  POST_COMMENT_FAILURE: 'POST_COMMENT_FAILURE',

  GET_COMMENT_REQUEST: 'GET_COMMENT_REQUEST',
  GET_COMMENT_SUCCESS: 'GET_COMMENT_SUCCESS',
  GET_COMMENT_FAILURE: 'GET_COMMENT_FAILURE',

  GET_ALL_COMMENTS_REQUEST: 'GET_ALL_COMMENTS_REQUEST',
  GET_ALL_COMMENTS_SUCCESS: 'GET_ALL_COMMENTS_SUCCESS',
  GET_ALL_COMMENTS_FAILURE: 'GET_ALL_COMMENTS_FAILURE',

  DELETE_COMMENT_REQUEST: 'DELETE_COMMENT_REQUEST',
  DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',

  GET_COMMENT_POST_REQUEST: 'GET_COMMENT_POST_REQUEST',
  GET_COMMENT_POST_SUCCESS: 'GET_COMMENT_POST_SUCCESS',
  GET_COMMENT_POST_FAILURE: 'GET_COMMENT_POST_FAILURE',
};
