export default {
  GET_REACTS_REQUEST: 'GET_REACTS_REQUEST',
  GET_REACTS_SUCCESS: 'GET_REACTS_SUCCESS',
  GET_REACTS_FAILURE: 'GET_REACTS_FAILURE',
  SET_POST_REACTS: 'SET_POST_REACTS',
  SET_REPLY_REACTS: 'SET_REPLY_REACTS',
  SET_COMMENT_REACTS: 'SET_COMMENT_REACTS',
  POST_REACT_REQUEST: 'POST_REACT_REQUEST',
  ADD_POST_REACT: 'ADD_POST_REACT',
  ADD_REPLY_REACT: 'ADD_REPLY_REACT',
  ADD_COMMENT_REACT: 'ADD_COMMENT_REACT',
};
