export default {
  GET_REPLIES_REQUEST: 'GET_REPLIES_REQUEST',
  GET_REPLIES_SUCCESS: 'GET_REPLIES_SUCCESS',
  GET_REPLIES_FAILURE: 'GET_REPLIES_FAILURE',
  POST_REPLY_REQUEST: 'POST_REPLY_REQUEST',
  POST_REPLY_SUCCESS: 'POST_REPLY_SUCCESS',
  POST_REPLY_FAILURE: 'POST_REPLY_FAILURE',
  SET_REPLIES: 'SET_REPLIES',
  ADD_REPLY: 'ADD_REPLY',
};
