export default {
  GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',

  GET_POST_REQUEST: 'GET_POST_REQUEST',
  GET_POST_SUCCESS: 'GET_POST_SUCCESS',
  GET_POST_FAILURE: 'GET_POST_FAILURE',

  GET_REPORTED_POST_REQUEST: 'GET_REPORTED_POST_REQUEST',
  GET_REPORTED_POST_SUCCESS: 'GET_REPORTED_POST_SUCCESS',
  GET_REPORTED_POST_FAILURE: 'GET_REPORTED_POST_FAILURE',

  GET_MORE_POSTS_REQUEST: 'GET_MORE_POSTS_REQUEST',
  GET_MORE_POSTS_SUCCESS: 'GET_MORE_POSTS_SUCCESS',
  GET_MORE_POSTS_FAILURE: 'GET_MORE_POSTS_FAILURE',

  POST_POST_REQUEST: 'POST_POST_REQUEST',
  POST_POST_SUCCESS: 'POST_POST_SUCCESS',
  POST_POST_FAILURE: 'POST_POST_FAILURE',

  DELETE_POST_REQUEST: 'DELETE_POST_REQUEST',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_FAILURE: 'DELETE_POST_FAILURE',

  PATCH_POST_REQUEST: 'PATCH_POST_REQUEST',
  PATCH_POST_SUCCESS: 'PATCH_POST_SUCCESS',
  PATCH_POST_FAILURE: 'PATCH_POST_FAILURE',
  
  REMOVE_POST: 'REMOVE_POST',
  UPDATE_POST: 'UPDATE_POST',
  SET_POSTS: 'SET_POSTS',
  ADD_POST: 'ADD_POST',
  COMPOSE_POST: 'COMPOSE_POST',
  ADD_POSTS: 'ADD_POSTS',
};
