export default {
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
  PATCH_USER_GROUP_REQUEST: 'PATCH_USER_GROUP_REQUEST',
  ADD_USER: 'ADD_USER',
};
