export default {
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  GET_GROUP_USERS_REQUEST: 'GET_GROUP_USERS_REQUEST',
  GET_GROUP_USERS_SUCCESS: 'GET_GROUP_USERS_SUCCESS',
  GET_GROUP_USERS_FAILURE: 'GET_GROUP_USERS_FAILURE',

  PATCH_USER_GROUP_REQUEST: 'PATCH_USER_GROUP_REQUEST',
  PATCH_USER_GROUP_SUCCESS: 'PATCH_USER_GROUP_SUCCESS',
  PATCH_USER_GROUP_FAILURE: 'PATCH_USER_GROUP_FAILURE',
  ADD_USER: 'ADD_USER',
};
