export default {
  GET_REPORT_VOTES_REQUEST: 'GET_REPORT_VOTES_REQUEST',
  GET_REPORT_VOTES_SUCCESS: 'GET_REPORT_VOTES_SUCCESS',
  GET_REPORT_VOTES_FAILURE: 'GET_REPORT_VOTES_FAILURE',
  PATCH_REPORT_VOTE_REQUEST: 'PATCH_REPORT_VOTE_REQUEST',
  PATCH_REPORT_VOTE_SUCCESS: 'PATCH_REPORT_VOTE_SUCCESS',
  PATCH_REPORT_VOTE_FAILURE: 'PATCH_REPORT_VOTE_FAILURE',
  DELETE_REPORT_VOTE_REQUEST: 'DELETE_REPORT_VOTE_REQUEST',
  DELETE_REPORT_VOTE_SUCCESS: 'DELETE_REPORT_VOTE_SUCCESS',
  DELETE_REPORT_VOTE_FAILURE: 'DELETE_REPORT_VOTE_FAILURE',
};
